Fix lit test run python errors
> TypeError: argument of type 'NoneType' is not iterable

This is because internally `lit` assumes that config.target_triple
cannot be `None`