Core: await narrowing cast warning
~~~
D:\a\swift-build\swift-build\SourceCache\swift-llbuild\lib\Core\BuildEngine.cpp(138): error C2397: conversion from 'int' to 'unsigned int' requires a narrowing conversion
~~~

This repairs a build error when building with `cl`.